name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github

  test:
    runs-on: ubuntu-latest
    needs: build 
    strategy:
      matrix:
        versions: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: install  Python 
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.versions }}
    - name: install requirements file
      run: pip -r requirements.txt
    - name: run test
      run: pytest text_app.py
